metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"

replication_factor = 1
rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "b30037b0e2f4bb15ba179a86033c869b306f26ca026c7a712d605f2a41bb4387"

compression_level = 2

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = "localhost.localdomain"

[s3_web]
bind_addr = "[::]:3902"
root_domain = "localhost.localdomain"
index = "index.html"

[admin]
api_bind_addr = "0.0.0.0:3903"
metrics_token = "metdx-demo"
admin_token = "metdx-demo"
